rails-studio/flix/config/routes.rb
Rails.application.routes.draw do
  resources :genres
  get "signup" => "users#new"
  get "signin" => "sessions#new"

  resources :users
  root "movies#index"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favorites
  end

  resources :sessions, only: [ :new, :create, :destroy ]
end

rails-studio/flix/app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "flash #{type}" %>
<% end %>

rails-studio/flix/app/views/layouts/_footer.html.erb
<footer>
    <p>
    Copyright &copy; <% Time.now.year %>
    <%= link_to "SRE East", "https://about.hgsgtk.me/" %>
    </p>
</footer>

rails-studio/flix/app/views/layouts/_header.html.erb
<header>
    <nav>
        <%= image_tag("logo.png", alt: "Super-Heroic Flix") %>
        <ul class="left">
            <li><%= nav_link_to "Released", movies_path %></li>
            <li><%= nav_link_to "Upcoming", filtered_movies_path(filter: "upcoming") %></li>
            <li><%= nav_link_to "Recent", filtered_movies_path(filter: "recent") %></li>
            <li><%= nav_link_to "Hits", filtered_movies_path(filter: "hits") %></li>
            <li><%= nav_link_to "Flops", filtered_movies_path(filter: "flops") %></li>
        </ul>
        <ul class="right">
            <% if current_user %>
                <li><%= link_to current_user.name, current_user %></li>
                <li><%= link_to "Account Settings", edit_user_path(current_user) %></li>
                <li>
                    <%= button_to "Sign Out", session_path(current_user), method: :delete %>
                </li>
            <% else %>
                <li><%= link_to "Sign In", signin_path %></li>
                <li><%= link_to "Sign Up", signup_path %></li>
            <% end %>
        </ul>
    </nav>
</header>

rails-studio/flix/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Super-Heroic Flix" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="content">
      <%= render "layouts/flash" %>

      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>